import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import Header from "@/components/navBar";
import Footer from "@/components/footer";
import {
  USER_SESSION_COOKIE_NAME,
  validateAndRefreshUserSession,
} from "@/lib/auth/userSession";
import type { NavUser } from "@/components/(auth)/userMenu";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const jwt = cookieStore.get(USER_SESSION_COOKIE_NAME)?.value;

  let user: NavUser | null = null;

  if (jwt) {
    try {
      const session = await validateAndRefreshUserSession(jwt);
      if (session) {
        user = {
          name: session.name,
          email: session.email,
          avatarUrl: session.avatarUrl,
        };
      }
    } catch (err) {
      console.error("[RootLayout] User session validation error:", err);
    }
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header user={user} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
